### ISSUE TITLE
Feature Request - retain command line parameters in CREATED_BY.txt

### ISSUE THREAD

**Issue by clunkclunk** [cktlco/crew-chief-autovoicepack#10]
I decided to kill the existing process I was working on all day so I could experiment with a bit of distributed CPU load, however when I went to resume it, I totally forgot what name I had used for `--your_name`. Also some users may have a number parameters used and a record of them might be useful.

The CREATED_BY.txt file seems to retain a little bit - with the `Voice name` written there, so it may be an appropriate place to record the various parameters in case they're needed for future reference.

**Comment by cktlco** [comment]
Great idea, thanks for creating an issue. Will be an easy addition and I will add it to the list.

**Comment by cktlco** [comment]
Hi, thanks for making this request. I've made the update in #31
