### ISSUE TITLE
Feature Request - show progression during phrase generation

### ISSUE THREAD

**Issue by Hawgk** [cktlco/crew-chief-autovoicepack#20]
Hello,
firstly thanks a lot for providing this awesome project. I'm currently exploring playing around with your tool.

During generation unfortunately there is no progression shown. I think it would be a great addition to help estimate how long a task will take. My suggestions would be having a timer for elapsed time and a percentage of the progression. Maybe even an estimation for time left based on progression and elapsed time.

Maybe something like this (last line added using arbitrary numbers):
`2024-11-09 12:03:09,998 [INFO] Considering phrase 851 - 'there's a slow car in turn 2' -> 'there's a slow car in turn 2'
2024-11-09 12:03:10,688 [INFO] Audio file created: ./output/Alex/voice/flags/slow_car_in_turn_2/3-a.wav
2024-11-09 12:03:11,439 [INFO] Audio file created: ./output/Alex/voice/flags/slow_car_in_turn_2/3-b.wav
2024-11-09 12:03:12,119 [INFO] Audio file created: ./output/Alex/voice/flags/slow_car_in_turn_2/3-c.wav
2024-11-09 12:03:12,121 [INFO] 851/1810 (47%) finished. Estimated time left ~20 Minutes.`

I maybe can have a look at it myself.

**Comment by cktlco** [comment]
Hi, great to see that you've gotten so far!

Thanks for contributing, this is a good suggestion and will be no problem to add. Generally, I'm running the app under `docker compose` with 7 replicas (for speed). In that case, each container doesn't know much about the progress of the others, thus the progress message won't be reliable, but it will still be useful when using a single container.

In the meantime, it's possible to estimate casually by looking at the numbers shown on "Considering phrase 851..." and knowing there are ~10K phrases * `variation_count` total wav files -- so ~30,000 files total by default, and thus 851/30000.

---

In separate good news, I've created a small pytorch ML model which does an excellent job of identifying the occasional "corrupt" and "weird" sounding audio clips so they can be automatically recreated during the generation process. It effectively detects the "weird repeated frequencies" and excess silence, but won't help with mispronunciations or similar speech failures.

I'll include a script so you can identify/delete the "bad" wav files in an existing voicepack directory. Removing the files and rerunning `generate_voice_pack.py` will recreate only the missing ones.

I'll probably have this integrated within the next few days.

**Comment by cktlco** [comment]
Hi @Hawgk -- I've added this capability, examples in the comment on #32
