### ISSUE TITLE
Docker Compose Fails Due To App Folder

### ISSUE THREAD

**Issue by ElRojo** [cktlco/crew-chief-autovoicepack#36]
[This line ](https://github.com/cktlco/crew-chief-autovoicepack/blob/main/docker-compose.yml#L45)in the docker-compose overwrites the entire app folder which holds image dependencies. I suggest adding an additional folder is all. I also suggest making this folder available on the Desktop by default so that it's a bit easier to find.

Original:

```
volumes:

      # output directory for the generated .wav files
      - C:\Users\MYUSER\crew-chief-autovoicepack:/app
```

Suggested fix:

``` 
 volumes:

      # output directory for the generated .wav files
      - C:\Users\MYUSER\Desktop\crew-chief-autovoicepack:/app/output
```

**Comment by cktlco** [comment]
Hi @ElRojo -- thanks for improving the project!

I agree with your fix and will make the change now. It's great to see someone using `docker-compose`!
